name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Cargo Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install frontend dependencies
        run: npm ci

      - name: Build JavaScript with Vite
        run: npx vite build

      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}